name: Go

on:
  workflow_call:

jobs:
  golangci:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Go
          uses: actions/setup-go@v4
          with: 
            go-version: '1.20'
            cache: true

        - name: Lint project
          uses: golangci/golangci-lint-action@v2
          with:
            version: latest

        - name: Build
          run: go build -v ./...
