name: Rust CI

on: [workflow_call]

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Cargo rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout project

      - uses: dtolnay/rust-toolchain@stable
        name: Install the Rust toolchain
  
      - uses: Swatinem/rust-cache@v2
        name: Use cached dependencies and artifacts
  
      - uses: arduino/setup-protoc@v2
        name: Install Protoc

      - name: Check formatting
        run: cargo fmt --check

      - name: Run lint
        run: cargo clippy -- -D warnings

      - name: Run unit tests
        run: cargo test --all --all-features -- --test-threads=1
